@startuml
'https://plantuml.com/class-diagram
class article{
-titre
-slug
-contenu
-datecreation
-datemodification
}

class niveau{
-intitule
-slug
}

class sequence{
-nom
-slug
-datecreation
}

niveau"1..1"--"0..*"sequence
sequence"1..1"--"0..*"article

@enduml